version: '3'
services:

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: voting-manager-db
    ports:
      - 27017:27017

  voting-app:
    build: .
    restart: always
    links:
      - mongodb
    ports:
      - 8080:8080
    depends_on:
      - mongodb